name: Report a bug 🐛
description: Report something that isn't working as expected
title: '[Bug]: '
type: 'bug'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report.
  - type: dropdown
    id: ibmer
    attributes:
      label: Are you an IBMer?
      options:
        - 'No'
        - 'Yes'
  - type: markdown
    attributes:
      value: 'If yes, you may also reach out directly via our internal Slack channel at #carbon-design-system.'
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Tell us more about the problem that you're running into"
      placeholder: What did you see? What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: client
    attributes:
      label: MCP client / AI application
      description: 'What MCP client or AI application were you using when you experienced the problem?'
      placeholder: Enter the MCP client or AI application name.
  - type: textarea
    id: prompt
    attributes:
      label: AI prompt
      description: 'What AI prompt did you use when you experienced the problem?'
      placeholder: Enter the AI prompt used.
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description:
        'How do we reproduce the error you described using the
        reproduction/example link above?'
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Suggested severity
      description:
        'Read more to understand our [severity levels](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/support.md#severity)'
      options:
        - 'Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.'
        - 'Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.'
        - 'Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.'
        - 'Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.'
  - type: input
    id: application
    attributes:
      label: Application / product
      description: "What application, product, or Carbon local system do you work on?"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-mcp/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
        - label:
            I checked the [current
            issues](https://github.com/carbon-design-system/carbon-mcp/issues) for
            duplicate problems
