name: Request support 🛟
description: Get help using Carbon MCP
title: '[Support]: '
type: 'support'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value:
        Use this template if you need help using Carbon MCP. If you are reporting a bug, please use the bug template instead.
  - type: dropdown
    id: ibmer
    attributes:
      label: Are you an IBMer?
      options:
        - 'No'
        - 'Yes'
  - type: markdown
    attributes:
      value: 'You may also reach out directly via our internal Slack channel at #carbon-design-system.'
  - type: textarea
    id: request
    attributes:
      label: What do you need help with?
      description: Describe what you're trying to do and where you're seeing an issue.
      placeholder: What are you trying to accomplish?
    validations:
      required: true
  - type: textarea
    id: client
    attributes:
      label: MCP client / AI application
      description: What MCP client or AI application are you using?
      placeholder: Enter the MCP client or AI application name.
    validations:
      required: true
  - type: textarea
    id: prompt
    attributes:
      label: AI prompt
      description: If applicable, share the prompt you used.
      placeholder: Enter the AI prompt used.
  - type: textarea
    id: expected
    attributes:
      label: Expected outcome
      description: What did you expect to happen?
      placeholder: Describe the expected behavior or result.
  - type: textarea
    id: actual
    attributes:
      label: Actual outcome
      description: What actually happened? Include error text if available.
      placeholder: Paste the error message or describe what you saw.
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs or attach screenshots. Please redact secrets.
      placeholder: Paste logs here (redact tokens, passwords, and private URLs).
  - type: input
    id: application
    attributes:
      label: Application / product
      description: What application, product, or Carbon local system do you work on?
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of Conduct](./.github/CODE_OF_CONDUCT.md)
          required: true

